import exportCmd from "./export.js";
import importCmd from "./import.js";
import mergeCmd from "./merge.js";

const help = {
  command: "manual <command>",
  aliases: ["m", "guide", "man", "instructions"],
  describe:
    "Outputs a detailed description of the specified command, above and beyond the autogenerated Yargs help messages.",
  handler,
  userManual:
    "Haha, very funny. Why would a user manual need its own user manual?",
};

export default help;

function isCommand(name) {
  return (module) => [...module.aliases, module.command.split(" ", 1)[0]].includes(name);
}

function handler(options) {
  const { command } = options;
  let targetCmd = [exportCmd, importCmd, mergeCmd, help].find(
    isCommand(command),
  );
  if (!targetCmd) {
    console.error(
      `The command name "${command}" does not correspond to any XenoYAML command or their aliases!`,
    );
    return;
  }

  console.log(`${targetCmd.command}
(Aliases: ${targetCmd.aliases.join(", ")});

${targetCmd.userManual || "No information is available for this command at the moment."}`);
}
